import Foundation

class ExerciseViewModel: ObservableObject {
    
    @Published var exercise: [ExerciseModel] = []
    
    init() {
        getExercise()
    }
    
    func getExercise() {
        let newExercise = [
            ExerciseModel(name: "LUNGES",
                          logo: "logoLunges",
                          videoName: "lunges",
                          steps: ["Stand with your feet shoulder width apart and your hands on your hips",
                                  "Step forward with your right leg and lower your body until your thigh is parallel to the floor",
                                  "Return and switch to the other leg",
                                  "Take a big step forward to make sure your front knee won't go over your toes",
                                  "Push through your front heel to go up",
                                  "Inhale when you go down and exhale when you go up"],
                          // This exercise strengthens your quadriceps, glutes and hamstrings
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "SQUATS",
                          logo: "logoSquats",
                          videoName: "squats",
                          steps: ["Stand with your feet shoulder width apart and your arms stretched forward",
                                  "Lower your body until your thighs are parallel to the floor",
                                  "Push through your heels and go back up again",
                                  "Keep your core tight",
                                  "Squeeze your glutes when you go up",
                                  "Inhale when you go down and exhale when you go up"],
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "BICYCLE CRUNCHES",
                          logo: "logoBycicleCrunches",
                          videoName: "bycicleCrunches",
                          steps: ["Lie on your back with your hands behind your ears and legs lifted up",
                                  "Try to alternately reach your opposite elbow to your opposite knee",
                                  "Put your hands behind your ears and don't interlock your fingers",
                                  "Open your elbows and avoid choking your neck",
                                  "Exhale as you lift your shoulders and inhale as you go back"],
                          // This exercise works your internal and external obliques
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "LEG RAISES",
                          logo: "logoLegRaises",
                          videoName: "legRaises",
                          steps: ["Lie on your back. Put your hands beneath your hips for support",
                                  "Lift your legs up until they form a right angle with the floor",
                                  "Slowly bring your legs back down and repeat",
                                  "You shouldn't feel any pressure in your chest and shoulders area",
                                  "Exhale when lifting your legs and inhale when lowering them"],
                          // This exercise targets your lower abdominals
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "SIDE-LYING LEG RAISES",
                          logo: "logoSideLyingLegRaises",
                          videoName: "sideLyingLegRaises",
                          steps: ["Lie on your side with your head rested on your left arm",
                                  "Lift your right leg up and down",
                                  "Exhale when lifting your leg and inhale when lowering it",
                                  "Make sure your leg goes straight up and down",
                                  "If you can't feel your glutes engage, you can slightly rotate your hips forward",
                                  "Keep your hips steady"],
                          //This is a great exercise for your glutes
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "JUMPING JACKS",
                          logo: "logoJumpingJacks",
                          videoName: "jumpingJacks",
                          steps: ["Jump up, spread your feet and bring your arms above your head",
                                  "Jump again, lower your arms and bring your legs together",
                                  "Inhale when you spread your feet and exhale when you pull them back"],
                          // This is a full body exercise that works all your muscle groups
                          targetMuscles: ["cardio", "legs", "arms"]),
            ExerciseModel(name: "STAR CRAWL",
                          logo: "logoStarCrawl",
                          videoName: "starCrawls",
                          steps: ["Start on all fours with your hands under your shoulders and your knee under your hips",
                                  "Put your left hand forward and bring your right knee to your right elbow",
                                  "Switch sides and move forward",
                                  "Then move backward in reverse way",
                                  "Repeat this exercise"],
                          // This is a good exercise for your core, legs and upper body
                          targetMuscles: ["abs", "legs", "arms"]),
            ExerciseModel(name: "SIDE CRUNCHES",
                          logo: "logoSideCrunches",
                          videoName: "sideCrunches",
                          steps: ["Lie on your right side with your right foot behind your left foot",
                                  "Put your left hand behind your head and your right hand on the left side of your oblique muscles",
                                  "Lift your right shoulder un off the floor",
                                  "Return and repeat",
                                  "Exhale as you raise up and inhale as you lower down"],
                          // This exercise targets your obliques
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "HIGH KNEES",
                          logo: "logoHighKnees",
                          videoName: "highKnees",
                          steps: ["Run in place while pulling your knees as high as possible with each step",
                                  "Keep your back straight",
                                  "Do it as fast as you can",
                                  "Breathe regularly"],
                          // This cardio exercise can strenghten your heart and lungs
                          targetMuscles: ["cardio"]),
            ExerciseModel(name: "MOUNTAIN CLIMBER",
                          logo: "logoMountainClimber",
                          videoName: "mountainClimber",
                          steps: ["Start in a push-up position",
                                  "Bring your right knee towards your chest and keep your left leg straight",
                                  "Quickly switch from one leg to other",
                                  "Bring your knees as close to your chest as possible",
                                  "Take steady and deep breaths"],
                          // This exercise can strenghten your cardiovascular system
                          targetMuscles: ["cardio", "abs"]),
            ExerciseModel(name: "LEG DUMBBELL CURLS",
                          logo: "logoLegDumbbellCurls",
                          videoName: "legDumbbellCurls",
                          steps: ["Stand against a wall",
                                  "Use your left hand to grab your right ankle with your palm facing up",
                                  "Pull your ankle towards your shoulder as much as you can, then slowly lower it",
                                  "Repeat the exercise",
                                  "Don't fully extend your biceps when lowering your ankle"],
                          // This exercise targets your biceps
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "HEEL TOUCHES",
                          logo: "logoHeelTouches",
                          videoName: "heelTouches",
                          steps: ["Lie on your back with your feet flat on the floor",
                                  "Slightly lift your shoulders off the floor",
                                  "Alternately reach your heels with your hands",
                                  "Exhale when touching your heels and inhale when coming back",
                                  "Keep your neck neutral",
                                  "Keep your lower back on the floor"],
                          // It's a great exercise for all of your abdominal muscles
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "PUSH-UPS",
                          logo: "logoPushUps",
                          videoName: "pushUps",
                          steps: ["Lay prone with your body in a straight line",
                                  "Lower down until your upper arms are parallel to the ground",
                                  "Push back up again",
                                  "Inhale when you go down and exhale when you go up",
                                  "If your elbows are close to your body, you'll focus more on your triceps, otherwise on your chest"],
                          // This exercise works your chest, abs and triceps
                          targetMuscles: ["abs", "arms"]),
            ExerciseModel(name: "ABDOMINAL CRUNCHES",
                          logo: "logoAbdominalCrunches",
                          videoName: "abdominalCrunches",
                          steps: ["Lie on your back with your knees bent and your arms streched forward",
                                  "Lift your upper body off the floor",
                                  "Hold for a few seconds and slowly return",
                                  "Fully engage your abs, don't use explosive strength",
                                  "Exhale as you lift your shoulders and inhale as you lower them"],
                          // This exercise primarily works your rectus abdominis
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "TRICEPS DIPS",
                          logo: "logoTricepsDips",
                          videoName: "tricepsDips",
                          steps: ["Press your hands on the edge of a chair",
                                  "Make sure there is enough distance between your body and the chair",
                                  "Slowly lower your body until your arms are about 90 degrees",
                                  "Then slowly go back",
                                  "Inhale when bending your arms and exhale when stretching them"],
                          // This exercise works your triceps
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "ALTERNATING HOOKS",
                          logo: "logoAlternatingHooks",
                          videoName: "alternatingHooks",
                          steps: ["Stand with your feet shoulder width apart",
                                  "Put your left hand behind your head and your right hand at your side",
                                  "Bend your body to the right and lower your right hand towards the floor",
                                  "Return, switch side and repeat",
                                  "Inhale when you bend down and exhale when you return"],
                          // This exercise works your shoulders
                          targetMuscles: ["cardio", "arms"]),
            ExerciseModel(name: "RUSSIAN TWISTS",
                          logo: "logoRussianTwists",
                          videoName: "russianTwists",
                          steps: ["Sit your feet slightly lifted and back tilted backward",
                                  "Hold your hands together and twist from side to side",
                                  "Exhale as you twist and inhale when you return",
                                  "Keep your legs still when twisting",
                                  "Keep your neck neutral",
                                  "Tighten your abs"],
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "PLANK",
                          logo: "logoPlank",
                          videoName: "plank",
                          steps: ["Start with your toes and forearms supported on the ground",
                                  "Place your elbows directly underneath your shoulders",
                                  "Keep your body in a straight line",
                                  "Tighten your core and glutes",
                                  "Breathe naturally",
                                  "You can lower your knees on the mat with your ankles crossed in the air if you feel it's too hard"],
                          // This exercise engages your abs and glutes
                          targetMuscles: ["abs", "legs"]),
            ExerciseModel(name: "INCHWORMS",
                          logo: "logoInchworms",
                          videoName: "inchworms",
                          steps: ["Stand with your feet shoulder width apart",
                                  "Put your hands on the floor and walk your hands forward as far as you can",
                                  "Then walk your hands back",
                                  "Try to keep your legs straight",
                                  "Tighten your core",
                                  "Breathe naturally"],
                          // This exerccise works your shoulders and streches your hamstrings
                          targetMuscles: ["cardio", "abs", "arms"]),
            ExerciseModel(name: "HOVER PUSH-UPS",
                          logo: "logoHoverPushUps",
                          videoName: "hoverPushUps",
                          steps: ["Start in the push-up position with your hands a little wider than shoulder width apart",
                                  "Lower down until your upper arms are parallel to the ground",
                                  "Shift your body to the left and then to the right",
                                  "Push your body up and repeat the exercise",
                                  "Breathe regularly",
                                  "Keep your body straight"],
                          // This is a good exercise for all your upper body muscles
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "SIT-UPS",
                          logo: "logoSitUps",
                          videoName: "sitUps",
                          steps: ["Lie on your back with your hands behind your ears",
                                  "Lift your upper body off the floor and slowly up to the sitting position",
                                  "Slowly return and repeat",
                                  "Don't tug your neck to get up",
                                  "Exhale as you come up and inhale as you return"],
                          // This exercise works your abs
                          targetMuscles: ["abs"]),
            ExerciseModel(name: "ARM SCISSORS",
                          logo: "logoArmScissors",
                          videoName: "armScissors",
                          steps: ["Stand with your feet shoulder width apart",
                                  "Lift your arms at shoulder height",
                                  "Cross your arms in front of you to make a letter 'X'",
                                  "Return and repeat",
                                  "Change the other arm on the top each time you cross",
                                  "Keep your arms at shoulder height"],
                          // This exercise works your deltoids
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "BUTT BRIDGE",
                          logo: "logoButtBridge",
                          videoName: "buttBridge",
                          steps: ["Lie on your back with your feet flat on the floor and arms at your sides",
                                  "Push your hips up, hold for 1 second and lower down",
                                  "Do it slowly to fully contract your glutes",
                                  "Squeeze your glutes when you push up",
                                  "Exhale when lifting your hips and inhale when lowering them"],
                          // This exercise really works your glutes
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "SKIPPING WITHOUT ROPE",
                          logo: "logoSkippingWithoutRope",
                          videoName: "skippingWithoutRope",
                          steps: ["Pretend to hold a skipping rope handle in each hand",
                                  "Jump and alternately land on the balls of your feet",
                                  "Rotating your wrists at the same time as if you were skipping a rope",
                                  "Don't let your heels touch the ground during skipping",
                                  "Breathe regularly"],
                          // This is a good warm-up exercise
                          targetMuscles: ["cardio"]),
            ExerciseModel(name: "MILITARY PUSH-UPS",
                          logo: "logoMilitaryPushUps",
                          videoName: "militaryPushUps",
                          steps: ["Start in a push-up position with your hands directly under your shoulders or as close as you can",
                                  "Bend your elbows and lower your body until your upper arms are parallel to the floor",
                                  "Push your body back and repeat the exercise",
                                  "Inhale when you go down and exhale when you go up",
                                  "Make sure your elbows are close to your body",
                                  "Keep your body straight"],
                          // This exercise works your triceps
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "ARM CURLS CRUNCHS",
                          logo: "logoArmCurlsCrunchs",
                          videoName: "armCurlsCrunches",
                          steps: ["Lie on your left side with you knees bent and lifted",
                                  "Grasp your left thigh with your left hand and put your right hand behind your head",
                                  "Pull your left thigh to raise your upper body",
                                  "Slowly return and repeat",
                                  "Use your elbow to support on the floor, instead of using your whole forearm",
                                  "Try to eliminate your abs when pulling your upper body up"],
                          // This exercise works your biceps
                          targetMuscles: ["arms"]),
            ExerciseModel(name: " DOORWAY CURLS",
                          logo: "logoDoorwayCurls",
                          videoName: "doorwayCurls",
                          steps: ["Stand with your left arm close to a wall",
                                  "Put your left hand on the wall and extend your arm",
                                  "Gently turn your body to the right",
                                  "Breathe naturally"],
                          // This exercise works your biceps
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "PUNCHES",
                          logo: "logoPunches",
                          videoName: "punches",
                          steps: ["Stand with one of your legs forward and your knees slightly bent",
                                  "Clench your fists in front of your face",
                                  "Alternately throw punches with your hands",
                                  "Do it as fast as you can",
                                  "Breathe regularly"],
                          // This exercise works your shoulders, biceps, triceps and forearms
                          targetMuscles: ["cardio", "arms"]),
            ExerciseModel(name: "ARM CIRCLES",
                          logo: "logoArmCircles",
                          videoName: "armCircles",
                          steps: ["Stand with your arms extended to the sides at shoulder height",
                                  "Move your arms counterclockwise in circles fast",
                                  "Try to do it as fast as you can",
                                  "Keep your arms straight",
                                  "Go from small circles to big circles",
                                  "Breathe regularly"],
                          // This exercise works your deltoids
                          targetMuscles: ["arms"]),
            ExerciseModel(name: "FROGGY GLUTE LIFTS",
                          logo: "logoFroggyGluteLifts",
                          videoName: "froggyGluteLifts",
                          steps: ["Lie on your stomach with your knees bent and apart",
                                  "Lift your heels up and down",
                                  "Repeat the exercise",
                                  "Exhale when lifting your feet and inhale when lowering them",
                                  "Keep your upper body still when lifting your feet"],
                          // This exercise targets your glutes and it's alo good for your lower back
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "STAR JUMPS",
                          logo: "logoStarJumps",
                          videoName: "starJumps",
                          steps: ["Start in a squat position with your hands touching your feet",
                                  "Jump up, spread your legs apart and raise your arms overhead to the sides",
                                  "Return and repeat",
                                  "Breathe regularly"],
                          // This is a cardio exercise that can help burn calories and fat
                          targetMuscles: ["cardio", "legs"]),
            ExerciseModel(name: "SUMO SQUAT CALF RAISES WITH WALL",
                          logo: "logoSumoSquatCalfRaisesWithWall",
                          videoName: "sumoSquatCalfRaisesWithWall",
                          steps: ["Stand with your hands on the wall and your feet a little wider than shoulder width apart",
                                  "Lower your body until your thighs are parallel to the floor",
                                  "Lift your heels up and down",
                                  "Exhale when you lift your heels and inhale when you lower them",
                                  "Don't lean your body forward",
                                  "Keep your upper body straight"],
                          // This exercise works your calves, glutes and inner thighs
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "PRONE FLUTTER KICKS",
                          logo: "logoProneFlutterKicks",
                          videoName: "proneFlutterKicks",
                          steps: ["Lie on your stomach with your legs slightly lifted and your chin on your arms",
                                  "Alternately lift your left and right legs",
                                  "Keep your core tight",
                                  "Keep your legs as straight as you can",
                                  "Breathe regularly"],
                          // This exercise focuses on your glutes and hamstrings
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "GLUTE KICKBACK CROSSOVER",
                          logo: "logoGluteKickbackCrossover",
                          videoName: "gluteKickbackCrossover",
                          steps: ["Start with your knees under your hips and your hands directly under your shoulders",
                                  "Lift your left leg backward, then lower it to your right side",
                                  "Lift it again and lower it straight down",
                                  "Repeat this exercise",
                                  "Don't let your left foot touch the floor",
                                  "Keep your left leg straight and squeeze your butt at the top",
                                  "Keep your back straight",
                                  "Perform this exercise with the other leg too"],
                          // This exercise works your glutes
                          targetMuscles: ["legs"]),
            ExerciseModel(name: "BURPEES",
                          logo: "logoBurpees",
                          videoName: "burpees",
                          steps: ["Stand with your feet shoulder width apart",
                                  "Put your hands on the ground and kick your feet backward",
                                  "Do a quick push-up, then jump up",
                                  "Bend your legs to get your hands on the floor instead of bending your body",
                                  "Do the steps of the exercise as quick as you can"],
                          // This is a full body exercise that works all your large muscles groups
                          targetMuscles: ["cardio", "legs", "arms"]),
            ExerciseModel(name: "JUMPING SQUATS",
                          logo: "logoJumpingSquats",
                          videoName: "jumpingSquats",
                          steps: ["Start in the squat position with you thighs parallel to the floor and your arms in front of your chest",
                                  "Jump up using your abdominal muscles for strength",
                                  "Land on the ball of your feet",
                                  "Return and repeat",
                                  "Inhale when you go down and exhale when you go up",
                                  "Your knees shouldn't go over your toes when squatting down"],
                          // This exercise works all your large muscle groups
                          targetMuscles: ["cardio", "legs"]),
            ExerciseModel(name: "SIDE HOPS",
                          logo: "logoSideHops",
                          videoName: "sideHops",
                          steps: ["Put your hands in front of you to keep balance",
                                  "Hop from side to side",
                                  "Land on the ball of your feet",
                                  "Breathe regularly"],
                          // This is a good cardio exercise that can get your legs involved and your heart rate up
                          targetMuscles: ["cardio"]),
            ExerciseModel(name: "SKATER JUMPS",
                          logo: "logoSkaterJumps",
                          videoName: "skaterJumps",
                          steps: ["Stand with your legs slightly bent and your arms at your sides",
                                  "Jump to the right, as you jump, bring your left foot behind you and your left arm in front of you",
                                  "Then jump to the other side. Repeat the exercise",
                                  "Keep your back flat and your core tight",
                                  "Breathe recularly"],
                          // This exercise is good for your cardiovascular system
                          targetMuscles: ["cardio"]),
            ExerciseModel(name: "QUICK FEET",
                          logo: "logoQuickFeet",
                          videoName: "quickFeet",
                          steps: ["Stand with your feet shoulder width apart",
                                  "Slightly bend your legs and lean your upper body forward",
                                  "Put your hands in front of you to keep balance",
                                  "Run in place quickly",
                                  "Keep your core tight and upper body still",
                                  "Take steady and deep breaths"],
                          // This is a cardio exercise that can warmup your body, work your quadriceps and calves, and improve your speed and agility
                          targetMuscles: ["cardio"]),
            ExerciseModel(name: "MOUNTAIN CLIMBER SQUAT THRUSTS",
                          logo: "logoMountainClimberSquatThrusts",
                          videoName: "mountainClimberSquatThrusts",
                          steps: ["Stand with your feet shoulder width apart",
                                  "Put your hands on the ground and kick your feet backward",
                                  "Bring your right knee towards your chest and keep your left leg straight",
                                  "Quickly switch legs and jump",
                                  "Repeat this exercise",
                                  "Do the steps of the exercise as quickly as possible",
                                  "Keep your core tight",
                                  "Breathe regularly"],
                          // This is a cardio exercise that works your full body and helps you burn fat
                          targetMuscles: ["cardio", "abs"])
        ]
        
        exercise.append(contentsOf: newExercise)
    }
}
