import Foundation

class WorkoutViewModel: ObservableObject {
    
    @Published var workout: [WorkoutModel] = []
    
    init() {
        getWorkout()
    }
    
    func getWorkout() {
        let newWorkout = [
            WorkoutModel(name: "WARM UP",
                         picture: "",
                         type: "cardio",
                         exercises: ["lunges", "squats", "bycicleCrunches", "legRaises"], // ???
                         ex: [ExerciseModel(name: "LUNGES",
                                            logo: "logoLunges",
                                            videoName: "lunges",
                                            steps: [""],
                                            targetMuscles: ["legs"]),
                              ExerciseModel(name: "SQUATS",
                                            logo: "logoSquats",
                                            videoName: "squats",
                                            steps: [""],
                                            targetMuscles: ["legs"]),
                              ExerciseModel(name: "BICYCLE CRUNCHES",
                                            logo: "logoBycicleCrunches",
                                            videoName: "bycicleCrunches",
                                            steps: [""],
                                            targetMuscles: ["abs"]),
                              ExerciseModel(name: "LEG RAISES",
                                            logo: "logoLegRaises",
                                            videoName: "legRaises",
                                            steps: [""],
                                            targetMuscles: ["abs"])
                         ]),
            WorkoutModel(name: "MORNING CARDIO",
                         picture: "",
                         type: "cardio",
                         exercises: ["","","",""],
                         ex: [
                            ExerciseModel(name: "JUMPING JACKS",
                                          logo: "logoJumpingJacks",
                                          videoName: "jumpingJacks",
                                          steps: [""],
                                          targetMuscles: ["cardio", "legs", "arms"]),
                            ExerciseModel(name: "BURPEES",
                                          logo: "logoBurpees",
                                          videoName: "burpees",
                                          steps: [""],
                                          targetMuscles: ["cardio", "legs", "arms"]),
                            ExerciseModel(name: "STAR JUMPS",
                                          logo: "logoStarJumps",
                                          videoName: "starJumps",
                                          steps: [""],
                                          targetMuscles: ["cardio", "legs"]),
                            ExerciseModel(name: "SKATER JUMPS",
                                          logo: "logoSkaterJumps",
                                          videoName: "skaterJumps",
                                          steps: [""],
                                          targetMuscles: ["cardio"]),
                            ExerciseModel(name: "QUICK FEET",
                                          logo: "logoQuickFeet",
                                          videoName: "quickFeet",
                                          steps: [""],
                                          targetMuscles: ["cardio"]),
                         ]),
            WorkoutModel(name: "LEGS ON FIRE",
                         picture: "",
                         type: "legs",
                         exercises: ["4", "5", "6"],
                         ex: [
                            ExerciseModel(name: "LUNGES",
                                          logo: "logoLunges",
                                          videoName: "lunges",
                                          steps: [""],
                                          targetMuscles: ["legs"]),
                            ExerciseModel(name: "SQUATS",
                                          logo: "logoSquats",
                                          videoName: "squats",
                                          steps: [""],
                                          targetMuscles: ["legs"]),
                            ExerciseModel(name: "SIDE-LYING LEG RAISES",
                                          logo: "logoSideLyingLegRaises",
                                          videoName: "sideLyingLegRaises",
                                          steps: [""],
                                          targetMuscles: ["legs"]),
                            ExerciseModel(name: "BUTT BRIDGE",
                                          logo: "logoButtBridge",
                                          videoName: "buttBridge",
                                          steps: [""],
                                          targetMuscles: ["legs"])
                         ]),
            WorkoutModel(name: "STRONGER ARMS",
                         picture: "",
                         type: "arms",
                         exercises: ["7", "8", "9"],
                         ex: [
                            ExerciseModel(name: "ARM SCISSORS",
                                          logo: "logoArmScissors",
                                          videoName: "armScissors",
                                          steps: [""],
                                          targetMuscles: ["arms"]),
                            ExerciseModel(name: "TRICEPS DIPS",
                                          logo: "logoTricepsDips",
                                          videoName: "tricepsDips",
                                          steps: [""],
                                          targetMuscles: ["arms"]),
                            ExerciseModel(name: "MILITARY PUSH-UPS",
                                          logo: "logoMilitaryPushUps",
                                          videoName: "militaryPushUps",
                                          steps: [""],
                                          targetMuscles: ["arms"]),
                            ExerciseModel(name: "ARM CURLS CRUNCHS",
                                          logo: "logoArmCurlsCrunchs",
                                          videoName: "armCurlsCrunches",
                                          steps: [""],
                                          targetMuscles: ["arms"]),
                            ExerciseModel(name: " DOORWAY CURLS",
                                          logo: "logoDoorwayCurls",
                                          videoName: "doorwayCurls",
                                          steps: [""],
                                          targetMuscles: ["arms"]),
                         ]),
            WorkoutModel(name: "ABS KILLER",
                         picture: "",
                         type: "abs",
                         exercises: ["10", "11", "12"],
                         ex: [
                            ExerciseModel(name: "LEG RAISES",
                                          logo: "logoLegRaises",
                                          videoName: "legRaises",
                                          steps: [""],
                                          targetMuscles: ["abs"]),
                            ExerciseModel(name: "ABDOMINAL CRUNCHES",
                                          logo: "logoAbdominalCrunches",
                                          videoName: "abdominalCrunches",
                                          steps: [""],
                                          targetMuscles: ["abs"]),
                            ExerciseModel(name: "HEEL TOUCHES",
                                          logo: "logoHeelTouches",
                                          videoName: "heelTouches",
                                          steps: [""],
                                          targetMuscles: ["abs"]),
                            ExerciseModel(name: "SIDE CRUNCHES",
                                          logo: "logoSideCrunches",
                                          videoName: "sideCrunches",
                                          steps: [""],
                                          targetMuscles: ["abs"]),
                         ]),
//            WorkoutModel(name: "BUTT & THIGHS",
//                          picture: "",
//                          type: "legs",
//                          exercises: ["13", "14", "15"], ex: <#[ExerciseModel]#>)
        ]
        
        workout.append(contentsOf: newWorkout)
    }
}





